# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Hue Quick Start iOS Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hue Quick Start iOS Swift
	pod ‘SwiftyJSON’
	pod 'Alamofire', '~> 3.4'
	
end
